
package cinemaproject;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class admin_login extends javax.swing.JFrame {

    public admin_login() {
        initComponents();
        intt();
    }
    public void intt(){
        setImage();
    }
    public void setImage(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo.png"));
        Image img = icon.getImage().getScaledInstance(logo_label.getWidth(), logo_label.getHeight(), Image.SCALE_SMOOTH);
        logo_label.setIcon(new ImageIcon(img));
        
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/images/cd.jpg"));
        Image img1 = icon1.getImage().getScaledInstance(cd.getWidth(), cd.getHeight(), Image.SCALE_SMOOTH);
        cd.setIcon(new ImageIcon(img1));
        
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/images/film.jpg"));
        Image img2 = icon2.getImage().getScaledInstance(film.getWidth(), film.getHeight(), Image.SCALE_SMOOTH);
        film.setIcon(new ImageIcon(img2));
        
        ImageIcon icon3 = new ImageIcon(getClass().getResource("/images/corn.jpg"));
        Image img3 = icon3.getImage().getScaledInstance(pop.getWidth(), pop.getHeight(), Image.SCALE_SMOOTH);
        pop.setIcon(new ImageIcon(img3)); 
        
        ImageIcon icon4 = new ImageIcon(getClass().getResource("/images/drink.jpg"));
        Image img4 = icon4.getImage().getScaledInstance(drink.getWidth(), drink.getHeight(), Image.SCALE_SMOOTH);
        drink.setIcon(new ImageIcon(img4)); 
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        reset_btn = new javax.swing.JButton();
        login_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        show_check_box = new javax.swing.JCheckBox();
        logo_label = new javax.swing.JLabel();
        cd = new javax.swing.JLabel();
        film = new javax.swing.JLabel();
        pop = new javax.swing.JLabel();
        drink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(805, 509));
        setMinimumSize(new java.awt.Dimension(805, 509));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(805, 509));
        jPanel1.setMinimumSize(new java.awt.Dimension(429, 606));
        jPanel1.setPreferredSize(new java.awt.Dimension(805, 509));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 320, 110, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 220, 120, 40);

        username_txt.setBackground(new java.awt.Color(204, 204, 204));
        username_txt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(username_txt);
        username_txt.setBounds(300, 210, 340, 60);

        reset_btn.setBackground(new java.awt.Color(197, 17, 17));
        reset_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(0, 0, 0));
        reset_btn.setText("Reset");
        reset_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_btnMouseClicked(evt);
            }
        });
        jPanel1.add(reset_btn);
        reset_btn.setBounds(470, 440, 170, 50);

        login_btn.setBackground(new java.awt.Color(204, 204, 204));
        login_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        login_btn.setForeground(new java.awt.Color(0, 0, 0));
        login_btn.setText("Login");
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
        });
        jPanel1.add(login_btn);
        login_btn.setBounds(160, 440, 170, 50);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("STZhongsong", 2, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" Staffs Only!!!");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 520, 810, 50);

        password_field.setBackground(new java.awt.Color(204, 204, 204));
        password_field.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        password_field.setCaretColor(new java.awt.Color(204, 204, 204));
        jPanel1.add(password_field);
        password_field.setBounds(300, 310, 340, 60);

        show_check_box.setBackground(new java.awt.Color(0, 0, 0));
        show_check_box.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        show_check_box.setForeground(new java.awt.Color(0, 0, 0));
        show_check_box.setText("Show password");
        show_check_box.setContentAreaFilled(false);
        show_check_box.setInheritsPopupMenu(true);
        show_check_box.setMargin(new java.awt.Insets(1, 1, 1, 1));
        show_check_box.setName(""); // NOI18N
        show_check_box.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        show_check_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_check_boxActionPerformed(evt);
            }
        });
        jPanel1.add(show_check_box);
        show_check_box.setBounds(300, 370, 200, 50);
        jPanel1.add(logo_label);
        logo_label.setBounds(230, 50, 340, 110);
        jPanel1.add(cd);
        cd.setBounds(30, 460, 120, 120);
        jPanel1.add(film);
        film.setBounds(630, 100, 210, 100);
        jPanel1.add(pop);
        pop.setBounds(30, 30, 170, 140);
        jPanel1.add(drink);
        drink.setBounds(690, 430, 80, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
        //get data from feild
        String username = username_txt.getText();
        char[] password = password_field.getPassword();
        String passwordStr = new String(password);
        
        if(username.equals("")  || (passwordStr.equals(""))){
            JOptionPane.showMessageDialog(this, "Please fill data first");
        }else if (username.equals("admin@pheak") && passwordStr.equals("LC-kh-001")){
            JOptionPane.showMessageDialog(this, "Login successfully!");
            menu_snack_drink obj = new menu_snack_drink();
            obj.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Wrong username or password!", "", JOptionPane.WARNING_MESSAGE);
        }  
    }//GEN-LAST:event_login_btnMouseClicked

    private void reset_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_btnMouseClicked
        username_txt.setText("");
        password_field.setText("");
    }//GEN-LAST:event_reset_btnMouseClicked

    private void show_check_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_check_boxActionPerformed
        if(show_check_box.isSelected()){
            password_field.setEchoChar((char)0);
        }else{
            password_field.setEchoChar('*');
        }
    }//GEN-LAST:event_show_check_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cd;
    private javax.swing.JLabel drink;
    private javax.swing.JLabel film;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel logo_label;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel pop;
    private javax.swing.JButton reset_btn;
    private javax.swing.JCheckBox show_check_box;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
